### ISSUE TITLE
rai client creates empty upload folder on windows

### ISSUE THREAD

**Issue by cwpearson** [rai-project/rai#34]
PUMPS 2019 students report that the windows client does not work. Current work-around is to use the linux client under the windows subsystem for linux.

**Comment by cwpearson** [comment]
The latest class binary seems to run, but always creates an empty compressed upload folder, with any of the following approaches:

Absolute path

```
.\rai.exe -p C:\Users\pearson\Downloads\gpu-algorithms-labs-master\labs\device_query
```

Relative path

```
.\rai.exe -p .\gpu-algorithms-labs-master\labs\device_query
```

Relative path with trailing slash

```
.\rai.exe -p .\gpu-algorithms-labs-master\labs\device_query\
```

Absolute path with trailing slash

```
.\rai.exe -p C:\Users\pearson\Downloads\gpu-algorithms-labs-master\labs\device_query\
```

**Comment by aschuh703** [comment]
Fixing windows was not a priority as Windows now includes a Linux subsystem. I verified that the current linux rai executable works on the current Windows Linux Subsystem with Ubuntu installed. I can fix this, but it has been a low priority.

**Comment by abduld** [comment]
let's fix this without relying on WLS. not everyone has one

**Comment by aschuh703** [comment]
Fixed. The working directory was being sanitized which converted it to a linux directory which was meaningless to Windows.
